version: '3.8'

services:
  backend:
    build:
      context: ./server
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - pos-network

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - pos-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_STRIPE_PUBLIC_KEY=${VITE_STRIPE_PUBLIC_KEY}
        - VITE_API_URL=${VITE_API_URL}
        - VITE_SOCKET_URL=${VITE_SOCKET_URL}
    ports:
      - "5173:5173"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - pos-network

volumes:
  mongo-data:

networks:
  pos-network:
    driver: bridge