version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "4000:4000"
    env_file:
      - .env  
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - pos-network

  frontend:
    build:
      context: ./client
      args:
        - VITE_STRIPE_PUBLISHABLE_KEY=pk_test_51Sx5sTPzorG2nWHVkDEKxfrOM83q8dao510Yur0skylQ2nHVTaPGxG648R88fdC17eXbiDpUl7TIXtsIRPNem2sk00NGTzqLvx
    ports:
      - "80:80"
      - "443:443" 
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro 
    env_file:
      - .env  
    depends_on:
      - backend
    networks:
      - pos-network

networks:
  pos-network:
    driver: bridge